"""
housekeeper.py — Reality-First Housekeeper for the IA-VISION / TrafficLab ecosystem.

Policy (from MACROGOAL REALITY-FIRST HOUSEKEEPER / BASELINE GUARD, 2026-09-25):

  - READ-ONLY by default. The only subcommand that may touch the filesystem is
    `delete --manifest <path> --i-have-reviewed`, and it requires an explicit
    manifest file that was previously generated by `gc --dry-run` AND reviewed.
  - UNKNOWN -> PRESERVE. If classification is uncertain, do not act.
  - Live runtime detection: if any of the watched processes (postgres, ollama,
    hermes, node, jupyter) is running, repo-adjacent paths are flagged
    RUNTIME_REFERENCED and skipped.
  - Memory is CONTEXT, not AUTHORITY. We never trust MEMORY.md for delete
    decisions; we trust origin/main, the live filesystem, and durable evidence.
  - One writer per mutable zone. This script only writes inside
    traficlab-factory/99_SYSTEM/housekeeper/output/ by default. It never touches
    product code.

Subcommands:
  scan         Discover repos, worktrees, branches, clones, DBs, Docker, processes.
  classify     Re-apply classification rules and emit a fresh manifest.
  gc --dry-run Emit a SAFE_DELETE_MANIFEST only — never delete.
  verify       Re-check that every candidate in a manifest is still safe.

Exit codes:
  0  ok
  1  user error (bad flags)
  2  live runtime detected — refused
  3  unsafe state — refused
  5  classification found nothing safe to do
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import os
import shutil
import sqlite3
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


# ---------- Constants ------------------------------------------------------

LIVE_RUNTIME_NAMES = {"postgres", "ollama", "hermes", "node", "jupyter"}

# Branch-name patterns we treat as evidence-of-supersede once merged into
# origin/main. These are NOT used to declare stale on their own — we still
# require ORPHAN_LOCAL_ONLY + not-merged-to-origin/main.
KNOWN_LANE_PATTERNS = (
    "lane-", "feat-fmi", "feat-geojson", "feat-opendrive", "feat-openscenario",
    "fix-lane", "g5-", "reconcile/", "audit/", "witness/", "evidence/",
)

PROTECTED_BRANCH_PATTERNS = (
    "main", "master", "develop", "release/",
    "feat/jupiter", "feat/wo", "feat/visor", "feat/evidence",
)

ALWAYS_PROTECTED_PATHS = (
    # Anything matching these path globs is NEVER a candidate, no matter what.
    "origin/main", "main", "master",
)


# ---------- Data model -----------------------------------------------------

@dataclasses.dataclass
class WorktreeRow:
    path: str
    repo: str
    sha: str | None
    branch: str | None
    dirty_files: int
    disk_bytes: int
    remote_status: str = "UNKNOWN"
    remote_reason: str = ""
    classification: str = "UNKNOWN_PRESERVE"
    classification_reason: str = ""
    confidence: str = "low"

    @property
    def disk_gb(self) -> float:
        return self.disk_bytes / 1024**3


# ---------- Utilities ------------------------------------------------------

def run(cmd: list[str], cwd: str | None = None, timeout: int = 60) -> tuple[int, str, str]:
    try:
        r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)
        return r.returncode, r.stdout.strip(), r.stderr.strip()
    except subprocess.TimeoutExpired:
        return -1, "", "timeout"
    except Exception as e:
        return -2, "", str(e)


def du_bytes(path: Path) -> int:
    total = 0
    try:
        for entry in path.rglob("*"):
            try:
                if entry.is_file() and not entry.is_symlink():
                    total += entry.stat().st_size
            except (OSError, PermissionError):
                pass
    except (OSError, PermissionError):
        pass
    return total


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def detect_live_runtime() -> set[str]:
    """Return the set of watched runtime names that are currently running."""
    rc, out, _ = run(["tasklist", "/FO", "CSV", "/NH"], timeout=15)
    found = set()
    for line in out.splitlines():
        parts = line.strip().split('","')
        if len(parts) < 1:
            continue
        name = parts[0].strip('"').lower()
        for k in LIVE_RUNTIME_NAMES:
            if name.startswith(k):
                found.add(k)
    return found


def is_branch_protected(branch: str) -> bool:
    b = branch.lower().replace("refs/heads/", "")
    if b in ("main", "master"):
        return True
    return any(b.startswith(p) for p in PROTECTED_BRANCH_PATTERNS)


# ---------- Discovery ------------------------------------------------------

def discover_worktrees(repos: list[Path]) -> list[WorktreeRow]:
    out = []
    for repo in repos:
        if not (repo / ".git").exists():
            continue
        rc, porcelain, _ = run(["git", "-C", str(repo), "worktree", "list", "--porcelain"], timeout=30)
        if not porcelain:
            continue
        for block in porcelain.split("\n\n"):
            if not block.strip():
                continue
            row = WorktreeRow(
                path="", repo=str(repo), sha=None, branch=None,
                dirty_files=0, disk_bytes=0,
            )
            for line in block.splitlines():
                if line.startswith("worktree "):
                    row.path = line[9:].strip()
                elif line.startswith("HEAD "):
                    row.sha = line[5:].strip()
                elif line.startswith("branch "):
                    row.branch = line[7:].strip()
            if not row.path:
                continue
            rc, dirty, _ = run(["git", "-C", row.path, "status", "--porcelain"], timeout=30)
            row.dirty_files = len(dirty.splitlines()) if dirty else 0
            p = Path(row.path)
            if p.exists():
                row.disk_bytes = du_bytes(p)
            out.append(row)
    return out


def check_remote(repo: Path, branch: str) -> tuple[bool, bool]:
    """Return (exists_on_origin, merged_into_origin_main)."""
    if not branch:
        return (False, False)
    b = branch.replace("refs/heads/", "")
    if b in ("main", "master"):
        return (True, True)
    rc, _, _ = run(["git", "-C", str(repo), "rev-parse", "--verify",
                    f"refs/remotes/origin/{b}"], timeout=10)
    on_origin = rc == 0
    if not on_origin:
        return (False, False)
    rc2, _, _ = run(["git", "-C", str(repo), "merge-base", "--is-ancestor",
                     f"refs/heads/{b}", "origin/main"], timeout=10)
    return (True, rc2 == 0)


def classify_worktree(row: WorktreeRow, repo_path: Path) -> WorktreeRow:
    """Apply the directive's classification tree."""
    branch = (row.branch or "").lower()
    # main/master take precedence over any pattern match
    if branch in ("refs/heads/main", "refs/heads/master", "main", "master"):
        row.classification = "ACTIVE_CANONICAL"
        row.classification_reason = f"on {branch}"
        row.confidence = "high"
        return row
    if is_branch_protected(branch):
        row.classification = "ACTIVE_STACKED"
        row.classification_reason = f"protected branch pattern: {branch}"
        row.confidence = "high"
        return row
    if row.dirty_files > 0:
        row.classification = "ACTIVE_DIRTY_OWNER_PRESERVE"
        row.classification_reason = f"dirty_files={row.dirty_files}"
        row.confidence = "high"
        return row
    on_origin, merged = check_remote(repo_path, row.branch or "")
    if merged:
        row.classification = "SUPERSEDED_KEEP_EVIDENCE"
        row.classification_reason = "merged into origin/main; evidence is in main"
        row.remote_status = "MERGED_INTO_MAIN"
        row.confidence = "high"
        return row
    if not on_origin and not merged:
        row.classification = "STALE_CANDIDATE"
        row.classification_reason = "not on origin, not merged, no dirty work"
        row.remote_status = "ORPHAN_LOCAL_ONLY"
        row.confidence = "med"
        return row
    if on_origin and not merged:
        row.classification = "ACTIVE_STACKED"
        row.classification_reason = "still open on origin, not yet merged"
        row.remote_status = "OPEN_ON_ORIGIN"
        row.confidence = "high"
        return row
    row.classification = "UNKNOWN_PRESERVE"
    row.classification_reason = "no remote info — default unsafe"
    row.confidence = "low"
    return row


# ---------- Subcommands ----------------------------------------------------

def cmd_scan(args: argparse.Namespace) -> int:
    repos = [Path(p).resolve() for p in args.repo]
    wts = discover_worktrees(repos)
    for w in wts:
        rp = Path(w.repo)
        classify_worktree(w, rp)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "scanned_at": now_iso(),
        "repos": [str(r) for r in repos],
        "worktrees": [dataclasses.asdict(w) for w in wts],
        "live_runtime_detected": list(detect_live_runtime()),
    }
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False))
    print(f"scanned {len(wts)} worktrees -> {out_path}")
    return 0


def cmd_classify(args: argparse.Namespace) -> int:
    """Re-classify an existing inventory JSON."""
    src = json.loads(Path(args.input).read_text())
    repos_by_path = {r: Path(r) for r in src.get("repos", [])}
    wts = [WorktreeRow(**{k: v for k, v in w.items() if k in WorktreeRow.__dataclass_fields__})
           for w in src["worktrees"]]
    for w in wts:
        rp = repos_by_path.get(w.repo) or Path(w.repo)
        classify_worktree(w, rp)
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps({"reclassified_at": now_iso(),
                                     "worktrees": [dataclasses.asdict(w) for w in wts]},
                                    indent=2, ensure_ascii=False))
    counts: dict[str, int] = {}
    for w in wts:
        counts[w.classification] = counts.get(w.classification, 0) + 1
    print(f"reclassified -> {out_path}")
    for k, v in sorted(counts.items(), key=lambda x: -x[1]):
        print(f"  {k:40s} {v}")
    return 0


def cmd_gc_dry_run(args: argparse.Namespace) -> int:
    """Emit SAFE_DELETE_MANIFEST only. Never delete."""
    live = detect_live_runtime()
    if live:
        print(f"REFUSED: live runtime detected: {sorted(live)}", file=sys.stderr)
        print("Refusing to emit a delete manifest while runtime is live.", file=sys.stderr)
        return 2
    src = json.loads(Path(args.input).read_text())
    candidates = []
    for w in src["worktrees"]:
        if w.get("classification") != "STALE_CANDIDATE":
            continue
        candidates.append({
            "path": w["path"],
            "repo": w["repo"],
            "branch": w.get("branch"),
            "sha": w.get("sha"),
            "disk_gb": round(w.get("disk_bytes", 0) / 1024**3, 4),
            "reason": w.get("classification_reason"),
            "remote_status": w.get("remote_status"),
        })
    manifest = {
        "manifest_id": f"manifest_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
        "generated_at": now_iso(),
        "policy": "DRY_RUN_MANIFEST — NOT EXECUTABLE. Delete gate requires CENSUS_PASS + "
                  "CLASSIFICATION_PASS + DEPENDENCY_CHECK_PASS + INDEPENDENT_REVIEW_PASS.",
        "candidates": candidates,
        "total_candidates": len(candidates),
        "total_recoverable_gb": round(sum(c["disk_gb"] for c in candidates), 4),
    }
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(manifest, indent=2, ensure_ascii=False))
    print(f"DRY-RUN manifest: {len(candidates)} candidates, "
          f"{manifest['total_recoverable_gb']:.2f} GB")
    print(f"  -> {out}")
    print(f"  NO DELETE PERFORMED.")
    return 0


def cmd_verify(args: argparse.Namespace) -> int:
    """Re-check that every candidate in a manifest is still safe."""
    manifest = json.loads(Path(args.manifest).read_text())
    live = detect_live_runtime()
    if live:
        print(f"REFUSED: live runtime detected: {sorted(live)}", file=sys.stderr)
        return 2
    failures = []
    for c in manifest["candidates"]:
        p = Path(c["path"])
        if not p.exists():
            failures.append({"path": c["path"], "reason": "path no longer exists"})
            continue
        # Confirm classification is still STALE_CANDIDATE
        row = WorktreeRow(
            path=str(p), repo=c["repo"], sha=None, branch=c.get("branch"),
            dirty_files=0, disk_bytes=0,
        )
        # Cheap re-classification: refetch git status + remote state
        rc, dirty, _ = run(["git", "-C", str(p), "status", "--porcelain"], timeout=30)
        row.dirty_files = len(dirty.splitlines()) if dirty else 0
        row.disk_bytes = du_bytes(p)
        if row.dirty_files > 0:
            failures.append({"path": c["path"], "reason": f"dirty_files={row.dirty_files} now"})
            continue
        classify_worktree(row, Path(c["repo"]))
        if row.classification != "STALE_CANDIDATE":
            failures.append({"path": c["path"],
                              "reason": f"reclassified to {row.classification}"})
    if failures:
        print(f"VERIFY FAILED: {len(failures)} candidates no longer safe")
        for f in failures[:20]:
            print(f"  - {f['path']}: {f['reason']}")
        return 3
    print(f"VERIFY OK: {len(manifest['candidates'])} candidates still safe")
    return 0


def cmd_delete(args: argparse.Namespace) -> int:
    """The ONLY subcommand that can mutate. Refuses unless --i-have-reviewed."""
    if not args.i_have_reviewed:
        print("REFUSED: pass --i-have-reviewed to acknowledge independent review passed.",
              file=sys.stderr)
        return 1
    live = detect_live_runtime()
    if live:
        print(f"REFUSED: live runtime detected: {sorted(live)}", file=sys.stderr)
        return 2
    manifest = json.loads(Path(args.manifest).read_text())
    rc = cmd_verify(argparse.Namespace(manifest=args.manifest))
    if rc != 0:
        print(f"REFUSED: verify failed for manifest {args.manifest}", file=sys.stderr)
        return rc
    deleted = 0
    errors = []
    for c in manifest["candidates"]:
        p = Path(c["path"])
        try:
            # Use git worktree remove first (deregisters from main repo)
            rp = Path(c["repo"])
            run(["git", "-C", str(rp), "worktree", "remove", "--force", str(p)],
                timeout=120)
            # If the directory still exists (e.g. empty), remove it
            if p.exists():
                shutil.rmtree(p, ignore_errors=True)
            deleted += 1
        except Exception as e:
            errors.append({"path": c["path"], "error": str(e)})
    print(f"deleted {deleted}/{len(manifest['candidates'])} worktrees")
    if errors:
        print(f"errors: {len(errors)}")
        for e in errors[:5]:
            print(f"  - {e['path']}: {e['error']}")
        return 3
    return 0


# ---------- Entry point ----------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="housekeeper", description=__doc__.splitlines()[0])
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("scan", help="discover repos, worktrees, branches, etc.")
    s.add_argument("--repo", action="append", required=True,
                   help="repository path (repeatable)")
    s.add_argument("--out", required=True, help="output JSON path")
    s.set_defaults(func=cmd_scan)

    s = sub.add_parser("classify", help="re-classify an existing inventory")
    s.add_argument("--input", required=True)
    s.add_argument("--output", required=True)
    s.set_defaults(func=cmd_classify)

    s = sub.add_parser("gc", help="garbage-collect (default: dry-run)")
    s.add_argument("--dry-run", action="store_true", default=True,
                   help="emit manifest only (default behavior)")
    s.add_argument("--input", required=True, help="inventory.json")
    s.add_argument("--output", required=True, help="manifest path")
    s.set_defaults(func=cmd_gc_dry_run)

    s = sub.add_parser("verify", help="re-check a manifest is still safe")
    s.add_argument("--manifest", required=True)
    s.set_defaults(func=cmd_verify)

    s = sub.add_parser("delete", help="DELETE (refuses unless --i-have-reviewed)")
    s.add_argument("--manifest", required=True)
    s.add_argument("--i-have-reviewed", action="store_true",
                   help="acknowledge independent review passed")
    s.set_defaults(func=cmd_delete)

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
